### PR TITLE
Testings

### PR DESCRIPTION
**Pull request by tariqmahmoodde**

### CODE REVIEW

**Comment by tariqmahmoodde** [comment]
Terraform Plan:

```
[command]/home/runner/work/_temp/62fa087d-a87e-4f70-992f-5e0859bb31fe/terraform-bin plan -no-color -out=tfplan
aws_security_group.example: Refreshing state... [id=sg-0954367191803e0a8]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
::debug::Terraform exited with code 0.
::debug::stdout: aws_security_group.example: Refreshing state... [id=sg-0954367191803e0a8]%0A%0ANo changes. Your infrastructure matches the configuration.%0A%0ATerraform has compared your real infrastructure against your configuration%0Aand found no differences, so no changes are needed.%0A
::debug::stderr: 
::debug::exitcode: 0
stdout<<ghadelimiter_eb6ba1ae-ccea-4069-92a7-779906660f28
aws_security_group.example: Refreshing state... [id=sg-0954367191803e0a8]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

ghadelimiter_eb6ba1ae-ccea-4069-92a7-779906660f28
stderr<<ghadelimiter_49437823-283c-41da-88d0-bc5980d1d7c9

ghadelimiter_49437823-283c-41da-88d0-bc5980d1d7c9
exitcode<<ghadelimiter_c1bd6bea-8047-4f92-aa55-49b470bb5f22
0
ghadelimiter_c1bd6bea-8047-4f92-aa55-49b470bb5f22
```

Plan saved to GitHub artifacts.

**Comment by tariqmahmoodde** [comment]
Terraform Plan:

```
[command]/home/runner/work/_temp/b213438f-070b-4bc9-9b6a-ce383d18bbc1/terraform-bin plan -no-color -out=tfplan
aws_security_group.example: Refreshing state... [id=sg-0954367191803e0a8]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
::debug::Terraform exited with code 0.
::debug::stdout: aws_security_group.example: Refreshing state... [id=sg-0954367191803e0a8]%0A%0ANo changes. Your infrastructure matches the configuration.%0A%0ATerraform has compared your real infrastructure against your configuration%0Aand found no differences, so no changes are needed.%0A
::debug::stderr: 
::debug::exitcode: 0
stdout<<ghadelimiter_6139e405-e401-4cfd-8e3d-2d38c0767a02
aws_security_group.example: Refreshing state... [id=sg-0954367191803e0a8]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

ghadelimiter_6139e405-e401-4cfd-8e3d-2d38c0767a02
stderr<<ghadelimiter_07d99354-b709-45eb-8eda-8091b3648975

ghadelimiter_07d99354-b709-45eb-8eda-8091b3648975
exitcode<<ghadelimiter_70d48ad2-882a-426b-b891-835d36a720f9
0
ghadelimiter_70d48ad2-882a-426b-b891-835d36a720f9
```

Plan saved to GitHub artifacts.

**Review by zeeemughal — APPROVED** [review]

**Comment by tariqmahmoodde** [comment]
Terraform Plan for `Directory: resources` and `Workspace: prod`:

```
[command]/home/runner/work/_temp/1091700c-30d5-4290-b563-792d3a6a6edf/terraform-bin plan -no-color -out=tfplan

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_security_group.example will be created
  + resource "aws_security_group" "example" {
      + arn                    = (known after apply)
      + description            = "Terraform security group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
      + name                   = "terra-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "example-security-group"
        }
      + tags_all               = {
          + "Name" = "example-security-group"
        }
      + vpc_id                 = "vpc-0198fdc6da92eb263"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + security_group_id = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"
::debug::Terraform exited with code 0.
::debug::stdout: %0ATerraform used the selected providers to generate the following execution%0Aplan. Resource actions are indicated with the following symbols:%0A  + create%0A%0ATerraform will perform the following actions:%0A%0A  # aws_security_group.example will be created%0A  + resource "aws_security_group" "example" {%0A      + arn                    = (known after apply)%0A      + description            = "Terraform security group"%0A      + egress                 = [%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 0%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "-1"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 0%0A            },%0A        ]%0A      + id                     = (known after apply)%0A      + ingress                = [%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 443%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "tcp"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 443%0A            },%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 80%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "tcp"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 80%0A            },%0A        ]%0A      + name                   = "terra-security-group"%0A      + name_prefix            = (known after apply)%0A      + owner_id               = (known after apply)%0A      + revoke_rules_on_delete = false%0A      + tags                   = {%0A          + "Name" = "example-security-group"%0A        }%0A      + tags_all               = {%0A          + "Name" = "example-security-group"%0A        }%0A      + vpc_id                 = "vpc-0198fdc6da92eb263"%0A    }%0A%0APlan: 1 to add, 0 to change, 0 to destroy.%0A%0AChanges to Outputs:%0A  + security_group_id = (known after apply)%0A%0A─────────────────────────────────────────────────────────────────────────────%0A%0ASaved the plan to: tfplan%0A%0ATo perform exactly these actions, run the following command to apply:%0A    terraform apply "tfplan"%0A
::debug::stderr: 
::debug::exitcode: 0
stdout<<ghadelimiter_52808428-9d27-4514-92b9-fd940889f2d7

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_security_group.example will be created
  + resource "aws_security_group" "example" {
      + arn                    = (known after apply)
      + description            = "Terraform security group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
      + name                   = "terra-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "example-security-group"
        }
      + tags_all               = {
          + "Name" = "example-security-group"
        }
      + vpc_id                 = "vpc-0198fdc6da92eb263"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + security_group_id = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"

ghadelimiter_52808428-9d27-4514-92b9-fd940889f2d7
stderr<<ghadelimiter_2a88636c-c6eb-4a90-a45e-87dfa371b5b8

ghadelimiter_2a88636c-c6eb-4a90-a45e-87dfa371b5b8
exitcode<<ghadelimiter_b4ea2b01-8cf6-40a5-a4c8-58c1602a2c47
0
ghadelimiter_b4ea2b01-8cf6-40a5-a4c8-58c1602a2c47
```

Plan saved to GitHub artifacts.

**Comment by tariqmahmoodde** [comment]
Terraform Plan for `Directory: resources` and `Workspace: stg`:

```
[command]/home/runner/work/_temp/3d1821e0-b10e-44e9-ae80-e3dc96ca0fc2/terraform-bin plan -no-color -out=tfplan

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_security_group.example will be created
  + resource "aws_security_group" "example" {
      + arn                    = (known after apply)
      + description            = "Terraform security group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
      + name                   = "terra-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "example-security-group"
        }
      + tags_all               = {
          + "Name" = "example-security-group"
        }
      + vpc_id                 = "vpc-0198fdc6da92eb263"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + security_group_id = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"
::debug::Terraform exited with code 0.
::debug::stdout: %0ATerraform used the selected providers to generate the following execution%0Aplan. Resource actions are indicated with the following symbols:%0A  + create%0A%0ATerraform will perform the following actions:%0A%0A  # aws_security_group.example will be created%0A  + resource "aws_security_group" "example" {%0A      + arn                    = (known after apply)%0A      + description            = "Terraform security group"%0A      + egress                 = [%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 0%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "-1"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 0%0A            },%0A        ]%0A      + id                     = (known after apply)%0A      + ingress                = [%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 443%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "tcp"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 443%0A            },%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 80%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "tcp"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 80%0A            },%0A        ]%0A      + name                   = "terra-security-group"%0A      + name_prefix            = (known after apply)%0A      + owner_id               = (known after apply)%0A      + revoke_rules_on_delete = false%0A      + tags                   = {%0A          + "Name" = "example-security-group"%0A        }%0A      + tags_all               = {%0A          + "Name" = "example-security-group"%0A        }%0A      + vpc_id                 = "vpc-0198fdc6da92eb263"%0A    }%0A%0APlan: 1 to add, 0 to change, 0 to destroy.%0A%0AChanges to Outputs:%0A  + security_group_id = (known after apply)%0A%0A─────────────────────────────────────────────────────────────────────────────%0A%0ASaved the plan to: tfplan%0A%0ATo perform exactly these actions, run the following command to apply:%0A    terraform apply "tfplan"%0A
::debug::stderr: 
::debug::exitcode: 0
stdout<<ghadelimiter_b1ae7fa8-47c2-40bc-8723-2faa670dd246

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_security_group.example will be created
  + resource "aws_security_group" "example" {
      + arn                    = (known after apply)
      + description            = "Terraform security group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
      + name                   = "terra-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "example-security-group"
        }
      + tags_all               = {
          + "Name" = "example-security-group"
        }
      + vpc_id                 = "vpc-0198fdc6da92eb263"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + security_group_id = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"

ghadelimiter_b1ae7fa8-47c2-40bc-8723-2faa670dd246
stderr<<ghadelimiter_536c4590-aa9f-4f84-b7ac-3e8f1df9c6ed

ghadelimiter_536c4590-aa9f-4f84-b7ac-3e8f1df9c6ed
exitcode<<ghadelimiter_2ad07e24-9214-44cb-9825-6a083c853b1f
0
ghadelimiter_2ad07e24-9214-44cb-9825-6a083c853b1f
```

Plan saved to GitHub artifacts.

**Comment by tariqmahmoodde** [comment]
Terraform Plan for `Directory: resources` and `Workspace: prod`:

```
[command]/home/runner/work/_temp/eb938234-b8e2-46ee-bd25-d4edcc6a398e/terraform-bin plan -no-color -out=tfplan

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_security_group.example will be created
  + resource "aws_security_group" "example" {
      + arn                    = (known after apply)
      + description            = "Terraform security group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
      + name                   = "prod-terra-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "example-security-group"
        }
      + tags_all               = {
          + "Name" = "example-security-group"
        }
      + vpc_id                 = "vpc-0198fdc6da92eb263"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + security_group_id = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"
Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: %0ATerraform used the selected providers to generate the following execution%0Aplan. Resource actions are indicated with the following symbols:%0A  + create%0A%0ATerraform will perform the following actions:%0A%0A  # aws_security_group.example will be created%0A  + resource "aws_security_group" "example" {%0A      + arn                    = (known after apply)%0A      + description            = "Terraform security group"%0A      + egress                 = [%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 0%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "-1"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 0%0A            },%0A        ]%0A      + id                     = (known after apply)%0A      + ingress                = [%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 443%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "tcp"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 443%0A            },%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 80%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "tcp"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 80%0A            },%0A        ]%0A      + name                   = "prod-terra-security-group"%0A      + name_prefix            = (known after apply)%0A      + owner_id               = (known after apply)%0A      + revoke_rules_on_delete = false%0A      + tags                   = {%0A          + "Name" = "example-security-group"%0A        }%0A      + tags_all               = {%0A          + "Name" = "example-security-group"%0A        }%0A      + vpc_id                 = "vpc-0198fdc6da92eb263"%0A    }%0A%0APlan: 1 to add, 0 to change, 0 to destroy.%0A%0AChanges to Outputs:%0A  + security_group_id = (known after apply)%0A%0A─────────────────────────────────────────────────────────────────────────────%0A%0ASaved the plan to: tfplan%0A%0ATo perform exactly these actions, run the following command to apply:%0A    terraform apply "tfplan"%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
stdout<<ghadelimiter_f2ec858c-eff8-408b-bdfa-bc21268a8b51

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_security_group.example will be created
  + resource "aws_security_group" "example" {
      + arn                    = (known after apply)
      + description            = "Terraform security group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
      + name                   = "prod-terra-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "example-security-group"
        }
      + tags_all               = {
          + "Name" = "example-security-group"
        }
      + vpc_id                 = "vpc-0198fdc6da92eb263"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + security_group_id = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"
Releasing state lock. This may take a few moments...

ghadelimiter_f2ec858c-eff8-408b-bdfa-bc21268a8b51
stderr<<ghadelimiter_25d4573e-9ef3-4235-ad2c-aae83d549be3

ghadelimiter_25d4573e-9ef3-4235-ad2c-aae83d549be3
exitcode<<ghadelimiter_c949a0a2-ec74-4a3d-90ea-f4dcb27ad1a5
0
ghadelimiter_c949a0a2-ec74-4a3d-90ea-f4dcb27ad1a5
```

Plan saved to GitHub artifacts.

**Comment by tariqmahmoodde** [comment]
Terraform Plan for `Directory: resources` and `Workspace: stg`:

```
[command]/home/runner/work/_temp/ac39feff-7f60-42c9-ba9b-0081292941b5/terraform-bin plan -no-color -out=tfplan

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_security_group.example will be created
  + resource "aws_security_group" "example" {
      + arn                    = (known after apply)
      + description            = "Terraform security group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
      + name                   = "stg-terra-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "example-security-group"
        }
      + tags_all               = {
          + "Name" = "example-security-group"
        }
      + vpc_id                 = "vpc-0198fdc6da92eb263"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + security_group_id = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"
Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: %0ATerraform used the selected providers to generate the following execution%0Aplan. Resource actions are indicated with the following symbols:%0A  + create%0A%0ATerraform will perform the following actions:%0A%0A  # aws_security_group.example will be created%0A  + resource "aws_security_group" "example" {%0A      + arn                    = (known after apply)%0A      + description            = "Terraform security group"%0A      + egress                 = [%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 0%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "-1"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 0%0A            },%0A        ]%0A      + id                     = (known after apply)%0A      + ingress                = [%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 443%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "tcp"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 443%0A            },%0A          + {%0A              + cidr_blocks      = [%0A                  + "0.0.0.0/0",%0A                ]%0A              + description      = ""%0A              + from_port        = 80%0A              + ipv6_cidr_blocks = []%0A              + prefix_list_ids  = []%0A              + protocol         = "tcp"%0A              + security_groups  = []%0A              + self             = false%0A              + to_port          = 80%0A            },%0A        ]%0A      + name                   = "stg-terra-security-group"%0A      + name_prefix            = (known after apply)%0A      + owner_id               = (known after apply)%0A      + revoke_rules_on_delete = false%0A      + tags                   = {%0A          + "Name" = "example-security-group"%0A        }%0A      + tags_all               = {%0A          + "Name" = "example-security-group"%0A        }%0A      + vpc_id                 = "vpc-0198fdc6da92eb263"%0A    }%0A%0APlan: 1 to add, 0 to change, 0 to destroy.%0A%0AChanges to Outputs:%0A  + security_group_id = (known after apply)%0A%0A─────────────────────────────────────────────────────────────────────────────%0A%0ASaved the plan to: tfplan%0A%0ATo perform exactly these actions, run the following command to apply:%0A    terraform apply "tfplan"%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
stdout<<ghadelimiter_22e8a671-f695-4213-a6f2-52f71cc17283

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_security_group.example will be created
  + resource "aws_security_group" "example" {
      + arn                    = (known after apply)
      + description            = "Terraform security group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
      + name                   = "stg-terra-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "example-security-group"
        }
      + tags_all               = {
          + "Name" = "example-security-group"
        }
      + vpc_id                 = "vpc-0198fdc6da92eb263"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + security_group_id = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"
Releasing state lock. This may take a few moments...

ghadelimiter_22e8a671-f695-4213-a6f2-52f71cc17283
stderr<<ghadelimiter_5e482fb5-d8da-4fb0-b2bd-0c301b939e19

ghadelimiter_5e482fb5-d8da-4fb0-b2bd-0c301b939e19
exitcode<<ghadelimiter_5591e909-2dda-410e-a1b6-0bbeb4f9d2a2
0
ghadelimiter_5591e909-2dda-410e-a1b6-0bbeb4f9d2a2
```

Plan saved to GitHub artifacts.

**Pull request closed without merging**
